name: "acala-release-note"
description: "Generate Release Note"
author: ermalkaleci
branding:
  icon: "package"
  color: "blue"

inputs:
  template:
    description: Template file path
    required: false
  chain:
    description: Network [karura | acala]
    required: true
  srtool_details:
    description: Srtool details path
    required: true
  subwasm_info:
    description: Subwasm info path
    required: true

outputs:
  release-note:
    description: Generated Release Note

runs:
  using: 'node20'
  main: 'dist/index.js'